# Generated by Django 3.0.3 on 2020-03-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.CharField(default='XS,S,M,L,XL', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
