# Generated by Django 3.0.3 on 2020-03-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200323_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.CharField(default='XS,S,M,L,XL', max_length=50),
        ),
    ]
