# Generated by Django 3.0.3 on 2020-03-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_left', models.PositiveIntegerField(default=0)),
                ('adjust_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('sale', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
