# Generated by Django 3.0.3 on 2020-03-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200318_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.CharField(blank=True, default='XS,S,M,L,XL', max_length=50, null=True),
        ),
    ]
